[Interface]
# Key for proton
# Bouncing = 3
# NAT-PMP (포트 포워딩) = off
# VPN Accelerator = off
PrivateKey = 8NbpJ0Yyig7TgPr8FsLtLm76wpxDkyDZA1RrOm8ZFk0=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# JP-FREE#18
PublicKey = 9Yy7/zeaFvKd/ETcLg0PvsJb5PVMj9dX4Wg7NVNVbCs=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.88.103.48:51820